[package]
name = "png_to_jpeg"
version = "0.1.0"
authors = ["Daniil Bereznev <daniil.bereznev@fora-soft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
